# Generated by terraform apply (inventory.tf) — do not hand-edit, re-run
# apply instead. Consumed by: ansible-playbook -i this-file
# playbooks/k8s_fleet.yml (ansible/roles/k8s_fleet).

[k8s_control_plane]
%{ for ip in control_plane_ips ~}
${ip} ansible_user=ubuntu
%{ endfor ~}

[k8s_workers]
%{ for ip in worker_ips ~}
${ip} ansible_user=ubuntu
%{ endfor ~}

[k8s_fleet:children]
k8s_control_plane
k8s_workers
