# Generated by terraform apply (inventory.tf) — do not hand-edit, re-run
# apply instead. Consumed by: ansible-playbook -i this-file
# playbooks/k8s_fleet.yml (ansible/roles/k8s_fleet).
#
# ansible_host is the public IP (SSH from outside the VPC);
# k3s_advertise_ip is the private IP k3s server/agent traffic actually
# uses between nodes, so intra-fleet k3s traffic never leaves the VPC.

[k8s_control_plane]
%{ for i, ip in control_plane_ips ~}
${ip} ansible_host=${ip} k3s_advertise_ip=${control_plane_private_ips[i]}
%{ endfor ~}

[k8s_workers]
%{ for i, ip in worker_ips ~}
${ip} ansible_host=${ip} k3s_advertise_ip=${worker_private_ips[i]}
%{ endfor ~}

[k8s_fleet:children]
k8s_control_plane
k8s_workers

[k8s_fleet:vars]
ansible_user=ubuntu
