apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.claimName }}
spec:
  accessModes:
    - {{ .Values.accessMode }}
  resources:
    requests:
      storage: {{ .Values.size }}
  {{- if .Values.storageClassName }}
  storageClassName: {{ .Values.storageClassName }}
  {{- end }}
